### ISSUE TITLE
本地怎么跑？

### ISSUE THREAD

**Issue by xiaohuozi500** [hqwuzhaoyi/GPTs-AI-Weaver#1]

**Comment by hqwuzhaoyi** [comment]
这个可以作为gpts的定义的
![CleanShot 2024-01-15 at 13 57 27](https://github.com/hqwuzhaoyi/GPTs-AI-Weaver/assets/44605072/4aa89b8d-ae8c-4dd7-9548-1d47a4bc4a2a)
